### ISSUE TITLE
Item sacrées non unbreakable

### ISSUE THREAD

**Issue by FlavGg** [RemainSky/RemainSky-Issues#1]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

FlavG_

### Votre pseudo discord

@flavg_

### Que s'est-il passé ?

Les items sacrées sont censé être unbreakable mais ils le sont pas

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

14h14 23/09/23

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/103735029/9a771a36-e739-42b0-aba1-6f98ad99aa80)

### Informations complémentaires

.

**Comment by SwartZCoding** [comment]
Cette pioche n'est pas un objet de toumai donc elle n'est pas incassable. Ce n'est pas un bug
