### ISSUE TITLE
[BUG] 1 des 2 pnj à la taverne ne fonctionne pas

### ISSUE THREAD

**Issue by FlavGg** [RemainSky/RemainSky-Issues#10]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

FlavG_

### Votre pseudo discord

@flavg_

### Que s'est-il passé ?

Quand on clique droit dessus on a un message d'erreur

### Comment reproduire le bug ?

clique droit sur le pnj 

### Qu'aurait-il dû arriver ?

ça aurait du ouvrir le menu taverne

### Date et heure de l'apparition problème

23/09/23 14h33

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/103735029/ff90fe46-96ef-4523-b4be-313c65637fec)

### Informations complémentaires

.

**Comment by NewZAZ** [comment]
@FlavGg Il suffit de bouger un peux, l'hitbox est cassée

**Comment by FlavGg** [comment]
> @FlavGg Il suffit de bouger un peux, l'hitbox est cassée

carré
