### ISSUE TITLE
[BUG + SUGGESTION] Les Danses

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#101]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

- le /iaemote ne fonctionne pas pour ouvrir le menu des dances.

- Remplacer le /iaemote par le /emotes pour ouvrir le menu des dances.

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Permission ajoutée. Il manque le /emote @NewZAZ

**Comment by NewZAZ** [comment]
impossible a ajouter actuellement
