### ISSUE TITLE
[ORTHOGRAPHE] les box (gain attribué lors d'ouverture)

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#102]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

**Box Vote (gain attribué) :**
- "tu viens d'obtenir 16 Sâbles des âmes" → "tu viens d'obtenir 16 Sables des âmes"
- "tu viens d'obtenir 1 livre raccomodage" → "... 1 livre raccommodage"
- "tu viens d'obtenir boite aux lettres" → "... Boîte aux lettres"

**Box Quête :**
- "tu viens d'obtenir 1 livre raccomodage" → "... 1 livre raccommodage"
- "tu viens d'obtenir un spâwner à vache" → "... un spawner à vache"
- "tu viens d'obtenir un spâwner à poule" → "... un spawner à poule"
- "tu viens d'obtenir un spâwner à cochon" → "... un spawner à cochon"

**Box Cosmétique :**
- "Tu viens d'obtenir le cosmetique x" → "... le cosmétique"
- "Tu viens d'obtenir le cosmetique Balloon Cluster" → "Tu viens d'obtenir le cosmétique Ballon"

**Box Commune :**
- "Tu viens d'obtenir trois pomme de Notch" → "... trois pommes de Notch"
- "Tu viens d'obtenir 2 entonnoir !" → "... 2 entonnoirs"
- "Tu viens d'obtenir 2 clés commune !" → "... 2 clés communes"

**Box Rare :**
- "Tu viens d'obtenir 4 RemainsBag !" → "... 4 RemainsBags !"
- "Tu viens d'obtenir deux spawners a araignée !" → "... deux spawners à araignée !
- "Tu viens d'obtenir deux spawners a squelette !" → "... deux spawners à squelette !
- "Tu viens d'obtenir trois spawners a araignée !" → "... trois spawners à zombie !
- "Tu viens d'obtenir pioche Rare !" → "... une pioche Rare"

**Box Danse :**
- Quand on reçoit une danse déjà obtenue → "... en guise de dédomagement !" = "... en guise de dédommagement !"

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé merci de votre report.
