### ISSUE TITLE
[SUGGESTION] /profil

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#103]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

**Ajouter dans le /profil :**

- Savoir combien de temps il nous reste sur le premium
- Savoir combien de temps il nous reste sur le grade possédé

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
good
