### ISSUE TITLE
[BUG] Anti Boost

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#105]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

- Miner au marteau un bloc entouré de netherite redonne les blocs de netherite pas cuit
- Activer un piston collant avec un slimeblock qui lui même est collé à un minerais de netherite permet de se boost dans le classement
- Activer un piston collant avec un HoneyBlock qui lui même est collé à un minerais de netherite permet de se boost dans le classement

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
good
