### ISSUE TITLE
[SUGGESTION] Boss Bar + /money

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#107]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Au lieu de faire 3 menus en haut pour les gemmes / monnaie / écailles, Mettre 1 seul menu regroupé avec les 4 monnaies qui affiche pendant 3 secondes une monnaie et ça passe à la suivante (Gemme / Ecaille / Monnaie / Essences)

Rajouter dans le /money le fait de pouvoir voir les gemmes, les écailles et les essences → ça pourrait être pratique.

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Il faut ajouter un /essence comme le /ecailles pour voir son nombre d'essences @NewZAZ. On ne touchera pas le hud
