### ISSUE TITLE
[ORTHOGRAPHE] /classement

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#108]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

**Classement Pêche** : "Pêcheur de maurue" → "Pêcheur de morues"

**Classement PVE** : "Tueur de Spider" → "Tueur d'araignée" + rajouter des "s" partout à la fin des noms des mobs

**Classement Vente** : Rajouter des "s" partout à la fin des noms des cultures

**Classement Minage** : "Récolteur d'or" → "Récolteur d'Or"

**"Classement Evènements" → "Classement Evénements"** : quand on clique sur un classement → "Evenement gagné" → "Evénements gagnés"

**Classement Métiers** : quand on clique sur un classement "Xp gagné" → "Xp gagnés"

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé! merci du report.
