### ISSUE TITLE
/sell all

### ISSUE THREAD

**Issue by corentaing10** [RemainSky/RemainSky-Issues#11]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Corentaing

### Votre pseudo discord

corentaing#8448

### Que s'est-il passé ?

Le /sell all ne fonctionne pa

### Comment reproduire le bug ?

juste en faisant le /sell all

### Qu'aurait-il dû arriver ?

vendre tout les items de l'inventaire

### Date et heure de l'apparition problème

23/09/23 à 14:33

### Serveur

Skyblock

**Comment by corentaing10** [comment]
Nous avons pas la permissions de faire la commande *

**Comment by SwartZCoding** [comment]
Fix.
