### ISSUE TITLE
[ORTHOGRAPHE] /jobs → "Comment augmenter son niveau ?"

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#110]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

**Enchanteur :**
- "Fabriquer des Tâbles d'enchantement" → "Fabriquer des Tables d'enchantement"

**Pêcheur :**
- **_Vendre / Pêcher_** des poissons : "Cod" → "Morue" / "Tropical Fish" → "Poisson tropical"

**Menuisier :**
- "Clic droit sur une buche avec une hâche" → "Clic droit sur une bûche avec une hâche"

**Chasseur :**
- Supprimer le "Participer à un volcan = 50XP" car il n'existe plus

**Agriculteur :**
- **_Vendre / récolter_** des plantations : "Cocoa Beans" → "Cacao" / "Nether Wart" → "Verrue du Nether" / "Sweet Berries" → "Baie sucrée" / "Beetroot" → "Betterave"

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report.
