### ISSUE TITLE
[ORTHOGRAPHE] le /explorateur

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#111]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

**Voir le classement** : Description = "... des joueurs étant le plus avancés" → "... des joueurs étant les plus avancés"

**Votre niveau :** Augmentez vos niveaux de métier" → "Augmenter vos niveaux de métier"

**Voir les récompenses :**
- Niveau 7/8/9 : "16 Graînes de ..." → "16 Graines de..."
- Niveau 38 : "1 Fragment de pépite de Volcanite" → "1 Fragment de Volcanite"
- Niveau 43 : "1 livre mending" → "1 livre raccommodage"
- Niveau 45 : "1 Hopper" → "1 Entonnoir"
- Niveau 45 : "1 Elytra" → 1 paire d'élytra"
- Niveau 51 : "3 Portail de l'end" → "3 Portails de l'end"
- Niveau 76 : "3 RemainsBag" → "3 RemainsBags"
- Niveau 78 : "2 pépite de volcanite" → "2 pépites de volcanite"
- Niveau 79 : "1 Clé Epique" → "2 Clés Epiques
- Niveau 80 : "2 Volcanite" → "2 Volcanites"

**On voit pas les récompenses du Niveau 82 à 100**
### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Niveau 38 : "1 Fragment de pépite de Volcanite" → "1 Fragment de Volcanite" -> C'est normal c'est le vrai nom fragment de pépite.
Pour du 82 au 100 normal il y en a pas.

Tous le reste corrigé. Merci de ton report.
