### ISSUE TITLE
[ORTHOGRAPHE] /is upgrade → Générateur

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#112]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

**Taux actuel :**

- "Deepslate" → "Ardoise des abîmes"
- "Andesite" → "Andésite"
- Indiquer le % de minerais d'émeraude dans le générateur car ce n'est pas écrit

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé ! merci du report.
