### ISSUE TITLE
[SUGGESTION] /shop

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#113]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Mettre dans la **catégorie "Divers"** les items qui sont dans la **catégorie "Blocs"** car c'est pas logique :
- Seau d'eau
- Seau de lave
- Toile d'araignée
- Pointed Dripstone
- Turtle Egg
- Seau de neige

Mettre les têtes de mobs + coeur de la mer dans la catégorie **"Loots"** car ils sont dans les **"Blocs"**

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé ! merci de ton report (J'ai laissé la Toile d'araignée et Pointed Dripstone car ca se pose)
