### ISSUE TITLE
[ORTHOGRAPHE] Shop d'île

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#114]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

- Quand on vend au joueur qui possède la boutique serait mieux de mettre "Vendre" à la place de "Revendre" sur le panneau.
- Quand on achète au joueur qui possède la boutiqueserait mieux de mettre "Acheter" à la place de "Racheter" sur le panneau.

- Quand on fait clic droit sur le panneau pour configurer la boutique et qu'on la met sur **"ACHAT"** , il est écrit :
    → Mode de la boutique : VENTE au lieu de ACHAT (voir screen pour comprendre)

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/145837411/002c130c-5a31-4026-8dbc-f3ab0fcdb50a)

**Comment by SwartZCoding** [comment]
Corrigé ! merci du report.
