### ISSUE TITLE
[ORTHOGRAPHE] Métiers Récompenses

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#115]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

**Ingénieur :**
- Niveau 2 : à supprimer car n'existe plus "Déblocage de la fabrication du Casino"
- Niveau 4/15 : "Fabriquer des décorations dans la tâble du menuisier à -25%" → "... la table du menuisier ..."
- Niveau 10 : à supprimer car n'existe plus "Déblocage de la fabrication de la Couveuse"

**Enchanteur :**
- Niveau 10 : "Déblocage de la tâble d'enchantement améliorée" → "... de la table d'enchantement .."

**Menuisier :**
- Niveau 5 : "Déblocage de la tâble de menuisier" → "... de la table de menuisier"

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé ! merci du report.
