### ISSUE TITLE
[BUG] /warp mine

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#116]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

- Par moment quand on saute dans le trou pour accéder à la mine, on prend des dégâts de chute.
- Arrivé dans la mine, on prend des dégâts de chute.
- La Pioche du Mineur perd aucune durabilité quand on mine avec dans la mine ou bien même sur notre île.
- Quand on farm au marteau à la mine, l'xp du marteau n'augmente pas.

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
marteau, normal vu qu'il peut pas être utilisé dans la mine, et la pioche du mineur normal elle est indestructible
