### ISSUE TITLE
[ORTHOGRAPHE] Box des Mondes

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#117]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

**Box Champi :**

_**Clic gauche sur la box :**_
- "Rune de Restoration" → "Rune de Restauration"
- "Clé Commune" → "2 Clés Communes"

**_Gains :_**
- "Tu viens d'obtenir une Rune De Replantation" → "... une Rune de Restauration"
- "Tu viens d'obtenir 2 clées communes" → "... 2 clés communes"

**Box  Abandonnée :**

_**Clic gauche sur la box :**_
- "120 Niveaux" → "140 Niveaux"

**_Gains :_**
- "Tu viens d'obtenir 2 clé rare !" → "... 2 clés rares !"
- "Tu viens d'obtenir 1 clée épique !" → "... 1 clé épique"

**Box Ténébreuse :**

_**Clic gauche sur la box :**_
- "Clé Rare" → "3 Clés Rares"
- "Clé Epique" → "2 Clés Epiques"

**_Gains :_**
- "Tu viens d'obtenir 2 clée épique !" → "... 2 clés épiques !"
- "Tu viens d'obtenir 2 clé rare !" → "... 2 clés rares !"
- "Tu viens d'obtenir une Rune De Replantation" → "... une Rune de Récolte" mais ça give une Rune de Restauration (donc à voir si la Rune est soit Récolte ou Restauration)

**CHANGER LES RUNES DE CHAQUE BOX CAR LES % ONT CHANGES !**

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé ! merci du report
