### ISSUE TITLE
[ORTHOGRAPHES] Monde Abandonné

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#118]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Lorsqu'il y a les invasions il y a de nombreuses fautes dans le scoreboard :

- "20 Zombies mineur en 2 minutes" → "... Zombies mineurs .."
- "10 Zombies empoisonné en 1 minutes" → "... Zombies empoisonnés"

Vérifier pour les autres s'il n'y a pas de fautes aussi car je n'ai pas eu toutes les invasions je pense.

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/145837411/92fed1bf-28cc-4ed6-81d4-567dc2b08196)

**Comment by SwartZCoding** [comment]
Corrigé ! merci de ton report.
