### ISSUE TITLE
[ORTHOGRAPHE] Posage de spawner

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#119]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?
**Spawner posé dans le mauvais monde :**
- "Celui-ci est surement posable" → "Celui-ci est sûrement posable"

**Lorsqu'on shift + clic droit :**

**_Statistique du Spawner :_**
- "Mob AI désactivé : true" → "Mob AI désactivée : true"
- Traduire les "Conditions de Spawn"

**_Conditions d'apparition_** → **_Conditions d'apparitions_** :
- "Les entitées peuvent apparaître !" → "Les entités peuvent apparaître !"

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé !  merci du report
