### ISSUE TITLE
[BUG]  Champi

### ISSUE THREAD

**Issue by Matthlo** [RemainSky/RemainSky-Issues#12]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Devil_Mat

### Votre pseudo discord

Devil_Mat

### Que s'est-il passé ?

Des zoglins spawnent et les champi sautent bcp trop, vachement chiant a tuer et le taux de drops des items est trop bas

### Comment reproduire le bug ?

taper des champis, ou attendre que d'autres spawnent

### Qu'aurait-il dû arriver ?

ils ne sautent plus et aucun zoglin spawn

### Date et heure de l'apparition problème

23/09 à 14h39

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/70896724/33f5dfc2-00c9-4336-a4b9-fc6944188966)
![image](https://github.com/RemainSky/RemainSky-Issues/assets/70896724/338f7db1-b2fd-4eed-a50a-c2141f35808a)

**Comment by SwartZCoding** [comment]
Atténuation du bug.
