### ISSUE TITLE
[ORTHOGRAPHE] Boutique

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#120]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

**Boosters Monnaies :**
- Il est affiché qu'il coûte 500k mais à l'achat il coûte réellement 450k.

**RemainsBags :**
- "Ouvrez ces sacs mystèrieux..." → "Ouvrez ces sacs mystérieux..."

**Kits :**
- Haya : Contenu de ce Kit → "Pommes dorées (x4)" → "Pomme dorée (x4)"
- Enchanteur : Contenu de ce Kit → "Bouteilles d'xp" → "Bouteille d'xp" / "Livres" → "Livre" / "Livre Mending" → "Livre raccommodage"
- Architecte : Contenu de ce Kit → "StoneBrick" → "Pierre Taillée"

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé ! merci du report.
