### ISSUE TITLE
[BUG] Cooldown Kits / Commandes

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#121]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

- **Kit Mineur** → 8h de cooldown affiché mais n'a que 5h en réalité.
- **/repair all ou /repair** en étant TRex reste toujours à 4h au lieu de 30min comme il est affiché dans le /boutique

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé! m erci de ton report
