### ISSUE TITLE
[ORTHOGRAPHE] Table d'enchantement améliorée

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#122]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Lorsqu'on enchante un item quelconque :
- "Vous venez d'enchanter votre objet avec l'enchantment : x" → "... avec l'enchantement : x"

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé ! merci de ton report
