### ISSUE TITLE
[ORTHOGRAPHE] RemainsBag

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#123]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Dans la description du RemainsBag, il y est écrit :

- "Tenez votre chance" → "Tentez votre chance"
- "Clique droit pour ouvrir" → "Clic droit pour ouvrir"

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report.
