### ISSUE TITLE
[ORTHOGRAPHE] le /ah

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#124]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Modifier la "**Catégorie Arme**" → "Catégorie Armes" (voir screen)

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/145837411/71a114d4-7e12-4cc0-93e8-5922ede3bb3a)

**Comment by SwartZCoding** [comment]
Corrigé. Merci du report.
