### ISSUE TITLE
[BUG] Boosters

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#125]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Lorsqu'on essaie de réactiver un booster par dessus un autre, ça affiche 2 fois le même message dans le chat :
- "Vous ne pouvez pas activer ce booster !"

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

01/10

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
fix
