### ISSUE TITLE
[SUGGESTION] /taverne ou /warp taverne

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#126]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Indiquer dans le menu /taverne qu'on est limité qu'à 2 achats par île et même au /warp taverne afin que les joueurs soient tenus au courant.

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

01/10

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé !
