### ISSUE TITLE
[ORTHOGRAPHE] Création d'un warp

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#127]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

"Nouveau warp crée au coordonnées ..." → "Nouveau warp créé aux coordonnées ..." (voir screen pour comprendre svp)
commande /is setwarp [nom]

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

01/10

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/145837411/e9540b2b-f33f-42cd-8b0e-e00e90cca485)

**Comment by SwartZCoding** [comment]
Corrigé merci de ton report.
