### ISSUE TITLE
[BUG] Table du Menuisier

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#129]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Lors d'un craft d'un bloc de décoration dans la Table du Menuisier, on a 50% de chance d'obtenir de l'argent mais il n'est pas indiqué combien.

- _**Niveau 10 :**_ "50% de chance d'obtenir de l'argent en fabriquant un bloc de décoration dans la table du menuisier."
→ Sauf que j'ai crafté 8 tables par exemple et je n'ai pas obtenu d'argent sur ces 8 crafts.

Le gain d'argent est trop cheaté → avec 6,4k on achète 1 stack de Dark Oak Log = Possibilité de craft 6 tables
On peut donc gagner 18k comme 6k et le plus souvent on gagne 12k donc on double notre argent.
Il faut donc réduire le gain d'argent obtenu lorsqu'on craft une décoration.

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

01/10

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
c'est 3000

**Comment by NewZAZ** [comment]
perso je reçois bien les 3000

**Comment by SwartZCoding** [comment]
Toujours pas fix visiblement d'après @S4maZz.

**Comment by NewZAZ** [comment]
Il n'y a pas de bug mais un problème d'économie @SwartZCoding

**Comment by SwartZCoding** [comment]
Corrigé.
