### ISSUE TITLE
[BUG] Quest invasion champi

### ISSUE THREAD

**Issue by FlavGg** [RemainSky/RemainSky-Issues#13]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

FlavG_

### Votre pseudo discord

@flavg_

### Que s'est-il passé ?

L'invasion champignon ( la quest tuer 20 champi en 4mn ) fonctionne que avec les grand champi est pas les petits 

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

ça aurai du augmenter la quest

### Date et heure de l'apparition problème

14h38 23/09/23

### Serveur

Skyblock

### Screen / vidéo

marche pas avec : 
![image](https://github.com/RemainSky/RemainSky-Issues/assets/103735029/78d321fa-9154-4bbd-a5a3-360a53f03e4c)

### Informations complémentaires

.

**Comment by SwartZCoding** [comment]
Ce n'est pas un bug, c'est une quête grand champi. On va ajouter la précision aux énoncés.

**Comment by SwartZCoding** [comment]
Corrigé. Merci de ton report.
