### ISSUE TITLE
[BUG] /Shop prix de revente bloc

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#130]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

**Pour l'ingénieur :**

Niveau 10 : "+10% du prix de vente dans la catégorie Blocs" → Ce boost n'est pas appliqué.
Niveau 20 : "+25% du prix de vente dans la catégorie Blocs" → Ce boost n'est pas appliqué.

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

01/10

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
good
