### ISSUE TITLE
[ORTHOGRAPHE] Les Succès

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#131]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

- Menuisier # 9 : "tâble du charpentier" → "table du menuisier"
- Pêcheur # 6 : "Pêcher 1 poissons-tropicaux" → "Pêcher 1 poisson tropical"
- Pêcheur # 2 : "Pêcher 7 morrues" → "Pêcher 7 morues"
- Pêcheur # 3 : "Cuire 7 morrues" → "Cuire 7 morues"
- Enchanteur # 8 : "Réparer 1 objets avec le réparateur" → "Réparer 1 objet.."
- Ingénieur # 8 : "Réparer 1 objets avec le réparateur" → "Réparer 1 objet.."
- Ingénieur # 7 : "Désenchanter 1 objets avec le désenchanteur" → "Désenchanter 1 objet..."
- Chasseur # 9 : "Tuer 1 tortues" → "Tuer 1 tortue"
- Chasseur # 10 : "Terminer 1 primes" → "Terminer 1 prime"

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

01/10

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Certains ne sont pas des erreurs. C'est juste à cause du boost pour la bêta qui affiche 1 seul objet avec un S.
