### ISSUE TITLE
[ORTHOGRAPHE] BackPack Agriculture / Minage

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#132]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

"Vendre tous le contenu du sac à..." → "Vendre tout le contnu du sac à ..."

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

01/10

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé merci de ton report.
