### ISSUE TITLE
[ORTHOGRAPHE] Boutique Booster

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#137]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

"Vous n'avez pas assez de d'argent pour acheter ce boosters" → "Vous n'avez pas assez d'argent pour acheter ce booster"

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

02/10

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/145837411/8c6d7373-4f2e-429e-b439-d814f7bb1aba)

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report.
