### ISSUE TITLE
[BUG] Faute d'orthographe

### ISSUE THREAD

**Issue by LupusArctos4** [RemainSky/RemainSky-Issues#14]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

darkshadows267

### Votre pseudo discord

loic_darkwolf

### Que s'est-il passé ?

une clé ne prend pas de "e" à la fin

### Comment reproduire le bug ?

1. /jobs
2. catégorie Enchanteur
3. section Récompenses
4. Page Suivante
5. Pallier niveau 17

### Qu'aurait-il dû arriver ?

une clé devrait être écrit sans "e" à la fin

### Date et heure de l'apparition problème

23/09/2023 08:42 (heure canadienne) 

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/124496446/01466594-1fb4-4357-9ee3-33664070e554)

**Comment by SwartZCoding** [comment]
Corrigé au prochain reboot. Merci de ton report :) !
