### ISSUE TITLE
[BUG GRAPHIQUE] Smiting Table

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#140]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

- Il faut refaire l'interface graphique de la Smiting Table car en 1.20 la fonction de la netherite a changé. (voir screen)

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

03/10

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/145837411/0bb768dd-bca5-45d9-9eb3-b83f9328c811)

**Comment by SwartZCoding** [comment]
Corrigé !
