### ISSUE TITLE
[BUG] Craft BackPack

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#141]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

- Le craft du BackPack Mineur ne fonctionne pas → Mettre le craft à jour (si c'est fragment ou pépite)

- Le craft du BackPack Agriculture ne fonctionne pas → Mettre le craft à jour (si c'est fragment ou pépite)

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

03/10

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Grosse update du WIKI à prévoir.

**Comment by SwartZCoding** [comment]
Corrigé dans le prochain wiki disponible à l'open.
