### ISSUE TITLE
[BUG] Backpack lore fail

### ISSUE THREAD

**Issue by SwartZCoding** [RemainSky/RemainSky-Issues#142]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SwartZ_

### Votre pseudo discord

Anto'

### Que s'est-il passé ?

https://cdn.discordapp.com/attachments/820731653609357313/1162684048636915802/image.png?ex=653cd4e6&is=652a5fe6&hm=59b251a09ca89f3daf1e25ea094449bc68a56f657c314e680a8cfb6465dacc5b&

### Comment reproduire le bug ?

Craft un backpack

### Qu'aurait-il dû arriver ?

Ne pas avoir %level% dans la lore mais 1

### Date et heure de l'apparition problème

111111111

### Serveur

Skyblock

### Screen / vidéo

https://cdn.discordapp.com/attachments/820731653609357313/1162684048636915802/image.png?ex=653cd4e6&is=652a5fe6&hm=59b251a09ca89f3daf1e25ea094449bc68a56f657c314e680a8cfb6465dacc5b&

**Comment by NewZAZ** [comment]
fix
