### ISSUE TITLE
[BUG XP METIER] Vente de melon

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#143]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Une tranche de pastèque se vend à 0,02 xp au lieu de 0,04 xp

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

02/12

### Serveur

Skyblock

**Comment by S4maZz** [comment]
C'est même bug pour tous les items du métier genre ça donne pas la bonne xp quand on vend, à vérifier pour tous les métiers.

**Comment by NewZAZ** [comment]
C'est le métier d'explorateur et non tes jobs
