### ISSUE TITLE
[BUG] /repair

### ISSUE THREAD

**Issue by LVeloute** [RemainSky/RemainSky-Issues#15]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

LVeloute

### Votre pseudo discord

velouté

### Que s'est-il passé ?

Le /repair et le /repair all ne marche pas sur les item sacré

### Comment reproduire le bug ?

/repair sur un item sacré

### Qu'aurait-il dû arriver ?

reparer la dura l'item

### Date et heure de l'apparition problème

23/09 14:44

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
Ce n'est pas un bug, mais les items sacrée sont indestructible maintenant
