### ISSUE TITLE
[BUG] Quest

### ISSUE THREAD

**Issue by LupusArctos4** [RemainSky/RemainSky-Issues#16]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

darkshadows267

### Votre pseudo discord

loic_darkwolf

### Que s'est-il passé ?

la commande n'existe pas quand on fait click droit sur le pnj du spawn

### Comment reproduire le bug ?

1. faire click droit sur le pnj quetes au spawn

### Qu'aurait-il dû arriver ?

ca devrait nous ouvrir une interface

### Date et heure de l'apparition problème

23/09/2023 08:46 (heure canadienne) 

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/124496446/389d9ac3-b5c3-4db6-8e2a-eaee66fc1341)

**Comment by SwartZCoding** [comment]
Les quêtes sont désactivés pour la bêta. Ce n'est donc pas un bug. Merci du report !
