### ISSUE TITLE
[BUG] vote & gagne

### ISSUE THREAD

**Issue by LupusArctos4** [RemainSky/RemainSky-Issues#18]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

darkshadows267

### Votre pseudo discord

loic_darkwolf

### Que s'est-il passé ?

clicker sur sur pnj du spawn ou faire /vote ne fait rien

### Comment reproduire le bug ?

1. click droit sur le pnj au spawn Vote & Gagne

### Qu'aurait-il dû arriver ?

ca devrait nous faire quelque chose, soit nous ouvrir une interface pour le vote soit nous donner un lien (je ne sais pas comment ici ca fonctionne vu que je n'ai jamais jouer a la v1)

### Date et heure de l'apparition problème

23/09/2023 08:52 (heure canadienne) 

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
@LupusArctos4 pour ma part ça fonctionne bien

**Comment by LupusArctos4** [comment]
ok bas bizarre alors
