### ISSUE TITLE
[BUG] /profil

### ISSUE THREAD

**Issue by Matthlo** [RemainSky/RemainSky-Issues#19]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Devil_Mat

### Votre pseudo discord

Devil_Mat

### Que s'est-il passé ?

/profil n'existe pas (c'est /profile Pseudo)

### Comment reproduire le bug ?

essayez de faire /profil, puis /profil pseudo, puis /profile et /profile pseudo

### Qu'aurait-il dû arriver ?

On devrait pouvoir faire toutes les commandes, et que sans arguments ça ouvre notre propre profil aulieu du message d'erreur

### Date et heure de l'apparition problème

23/09 à 14h58

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/70896724/14a0c49b-3caf-4cc4-8aa8-fcdde32554f8)
![image](https://github.com/RemainSky/RemainSky-Issues/assets/70896724/7f777b45-b42c-4d47-a780-b77fe462d8a4)

**Comment by SwartZCoding** [comment]
Fix au prochain reboot.

**Comment by NewZAZ** [comment]
fix
