### ISSUE TITLE
[BUG] Fautes / Traduction

### ISSUE THREAD

**Issue by Matthlo** [RemainSky/RemainSky-Issues#2]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Devil_Mat

### Votre pseudo discord

Devil_Mat

### Que s'est-il passé ?

Fautes de traduction sur la nether wart à mettre en français
Fautes sur morrue (il faut un R et non 2), et carotte non carrote

### Comment reproduire le bug ?

./events

### Qu'aurait-il dû arriver ?

nom en français et morue non morue, carotte non carrote

### Date et heure de l'apparition problème

23/09 à 14h16

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/70896724/faa1558d-7e32-4bd2-8b1a-fb983c1bc731)
![image](https://github.com/RemainSky/RemainSky-Issues/assets/70896724/6fafeece-4941-4314-877a-ada7fa2d8f2d)

**Comment by SwartZCoding** [comment]
Corrigé. Merci de ton report.
