### ISSUE TITLE
[BUG] /is create desert/mycel

### ISSUE THREAD

**Issue by LupusArctos4** [RemainSky/RemainSky-Issues#20]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

darkshadows267

### Votre pseudo discord

loic_darkwolf

### Que s'est-il passé ?

j'ai fait /is create desert et /is create mycel mais rien ne se passe

### Comment reproduire le bug ?

1. faire /is create desert/mycel

### Qu'aurait-il dû arriver ?

ça derait nous créer une is

### Date et heure de l'apparition problème

23/09/2023 08:59 (heure canadienne) 

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
Normal il y a que un seul type d'île @LupusArctos4

**Comment by LupusArctos4** [comment]
ok mais vu que ca m'en propose d'autre je me suis dit qu'il y en avait plus
