### ISSUE TITLE
[BUG] Salaire

### ISSUE THREAD

**Issue by FlavGg** [RemainSky/RemainSky-Issues#21]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

FlavG_

### Votre pseudo discord

@flavg_

### Que s'est-il passé ?

Le message salaire dans le chat me dit que j'ai gagner 0

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

ça aurait du me donner un certain nombre de monnaie

### Date et heure de l'apparition problème

20/09/23 15h00

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/103735029/f5fde6df-2055-4986-afa5-f5c7d80483f0)

### Informations complémentaires

.

**Comment by NewZAZ** [comment]
Fix prochain redem

**Comment by NewZAZ** [comment]
fix
