### ISSUE TITLE
[BUG] Maison des cosmétiques

### ISSUE THREAD

**Issue by FlavGg** [RemainSky/RemainSky-Issues#22]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

FlavG_

### Votre pseudo discord

@flavg_

### Que s'est-il passé ?

Quand on va sur le tapis rouge pour équiper les cosmétiques ça renvoi au spawn de la maison

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

ouvrir le menu cosmétique

### Date et heure de l'apparition problème

23/09/23 15h00

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Fix. Merci du report.
