### ISSUE TITLE
[BUG]  Oeuf de poule

### ISSUE THREAD

**Issue by Matthlo** [RemainSky/RemainSky-Issues#23]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Devil_Mat

### Votre pseudo discord

Devil_Mat

### Que s'est-il passé ?

Les poules pondent des oeufs stack par leur nombre

### Comment reproduire le bug ?

attendre qu'un stack de poule pondent

### Qu'aurait-il dû arriver ?

pas d'oeufs, ou 1seul pour éviter les lags et items inutile

### Date et heure de l'apparition problème

23/09 à 15h00

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/70896724/ed0e719c-3281-4d9b-b22a-10b65b71528c)

**Comment by SwartZCoding** [comment]
Corrigé merci de ton report !
