### ISSUE TITLE
[BUG] is top

### ISSUE THREAD

**Issue by FlavGg** [RemainSky/RemainSky-Issues#24]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

FlavG_

### Votre pseudo discord

@flavg_

### Que s'est-il passé ?

Le top is ne s'actualise pas après de longues minutes de plus je suis passé de 22pts à 12 alors que j'en ai 1k et plus

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

23/09/23 15h00

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/103735029/ecd759db-d5b5-449d-a097-6ebfe6b26931)

**Comment by NewZAZ** [comment]
@FlavGg il s'update toute les 5 minutes, et normal si tu es plus dans un classement ou tu as été dépasser tu perdra des points

**Comment by FlavGg** [comment]
> @FlavGg il s'update toute les 5 minutes, et normal si tu es plus dans un classement ou tu as été dépasser tu perdra des points

j'ai 3000 pts

**Comment by NewZAZ** [comment]
les blocs ne compte pas, maintenant c'est les points du /classement

**Comment by NewZAZ** [comment]
@FlavGg ducoup good ?
