### ISSUE TITLE
[BUG] Nom sac agriculteur

### ISSUE THREAD

**Issue by Matthlo** [RemainSky/RemainSky-Issues#25]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Devil_Mat

### Votre pseudo discord

Devil_Mat

### Que s'est-il passé ?

Soucis de nom

### Comment reproduire le bug ?

give un sac agriculture

### Qu'aurait-il dû arriver ?

il doit être nommé sac agriculture et non minage

### Date et heure de l'apparition problème

23/09 à 15h06

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/70896724/cd7cffcf-2e3a-4a5a-9200-16673f510f13)

**Comment by NewZAZ** [comment]
Fix prochain redémarrage merci !

**Comment by NewZAZ** [comment]
fix
