### ISSUE TITLE
[BUG] Affichage sur les hache modée

### ISSUE THREAD

**Issue by LVeloute** [RemainSky/RemainSky-Issues#26]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

LVeloute

### Votre pseudo discord

velouté

### Que s'est-il passé ?

inscription anormale sur les haches modé

### Comment reproduire le bug ?

mettre le curseur sur un hache a citrouille ou melon

### Qu'aurait-il dû arriver ?

pas de texte anormale

### Date et heure de l'apparition problème

15:15 23/09

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/145841404/42aa6ae9-7538-41d5-8c32-1b9d14707a3c)

**Comment by NewZAZ** [comment]
fix
