### ISSUE TITLE
[BUG] Hache Cacao 

### ISSUE THREAD

**Issue by Skiniix** [RemainSky/RemainSky-Issues#27]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Skiniix

### Votre pseudo discord

Skiniix

### Que s'est-il passé ?

La hache de cacao ne replante pas les cacaos.

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

Replanter le cacao cassé.

### Date et heure de l'apparition problème

23/09/23 à 15h15

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
Ce n'est pas un bug, mais un soucis d'affichage, c'est au niveau 2 que la hache replante

**Comment by Skiniix** [comment]
ça marche. Mais en cassant du cacao nous gagnons de l'xp d'agriculteur mais pas d'XP sur la hache.  @NewZAZ

**Comment by NewZAZ** [comment]
fix
