### ISSUE TITLE
[BUG] Hache du bucheron 

### ISSUE THREAD

**Issue by Skiniix** [RemainSky/RemainSky-Issues#28]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Skiniix

### Votre pseudo discord

Skiniix

### Que s'est-il passé ?

La hache du bucheron ne casse pas entièrement l'arbre. Mais l'arbre se casse que si on casse la buche au niveau des feuilles. Si nous cassons l'arbre à partir du premier bloc du tronc, l'arbre ne se casse pas. 

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

Casser l'arbre entier à partir du premier bloc. 

### Date et heure de l'apparition problème

23/09/23 à 15h20

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
@Skiniix c'est normal il y a une limite block. Si il a casser que un seul block c'est un bug sinon non

**Comment by Skiniix** [comment]
@NewZAZ Justement la hache ne casse qu'un seul bloc, si elle case le premier bloc de bois

**Comment by NewZAZ** [comment]
fix
