### ISSUE TITLE
[BUG] Vente de Nether Bricks au /shop abusé

### ISSUE THREAD

**Issue by ext0ller** [RemainSky/RemainSky-Issues#29]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

extoller

### Votre pseudo discord

extoller

### Que s'est-il passé ?

on peux vendre la nether bricks à 1k250 au /shop 
alors que sa se farm très rapidement 

### Comment reproduire le bug ?

acheter bois netherack /shop mettre dans un four et vendre nether bricks à 1k250

### Qu'aurait-il dû arriver ?

pas pouvoir vendre la nether brick ou réduire le prix

### Date et heure de l'apparition problème

23/09/23 à 15h

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
Fix ! merci
