### ISSUE TITLE
[BUG] Métier de pêcheur dans le "renforceur"

### ISSUE THREAD

**Issue by Skiniix** [RemainSky/RemainSky-Issues#3]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Skiniix

### Votre pseudo discord

Skiniix

### Que s'est-il passé ?

Dans le "renforceur", les blocs "vides" sont sûrement les mêmes que pour l'interface du métier pêcheur.

### Comment reproduire le bug ?

Ouvrir un renforceur

### Qu'aurait-il dû arriver ?

Ne rien avoir dans les cases "vides"

### Date et heure de l'apparition problème

23/09/23 à 14h15

### Serveur

Skyblock

### Screen / vidéo

![2023-09-23_14 13 06](https://github.com/RemainSky/RemainSky-Issues/assets/145837242/8c0cc6af-563b-494c-868e-f6938936ac24)

**Comment by Skiniix** [comment]
Idem pour le catalyseur, avec l'item papier : 
![2023-09-23_14 18 33](https://github.com/RemainSky/RemainSky-Issues/assets/145837242/af2699f5-15b4-41b5-a765-0dec97b9fd66)

**Comment by NewZAZ** [comment]
@SwartZCoding - Ajouter un nom et une description pour les 2 states

**Comment by NewZAZ** [comment]
fix
