### ISSUE TITLE
[BUG] itemsadder description

### ISSUE THREAD

**Issue by Endojoy** [RemainSky/RemainSky-Issues#30]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

EnjoyI

### Votre pseudo discord

endodoy

### Que s'est-il passé ?

Description du pack itemsadder non modifiée (pareil pour l'image).

### Comment reproduire le bug ?

....

### Qu'aurait-il dû arriver ?

.....

### Date et heure de l'apparition problème

23/09/2023 15h25

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/126188070/bf4746aa-0f6b-46ad-99ca-1ddec6203a43)

**Comment by SwartZCoding** [comment]
Corrigé. Merci du report.
