### ISSUE TITLE
[BUG] nom debutant

### ISSUE THREAD

**Issue by Matthlo** [RemainSky/RemainSky-Issues#31]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Devil_Mat

### Votre pseudo discord

Devil_Mat

### Que s'est-il passé ?

Bug dans le nom du prérequis du grade en cliquant sur expérimenté

### Comment reproduire le bug ?

./rang, être novice et cliquer sur expérimenté

### Qu'aurait-il dû arriver ?

avoir le vrai nom dans le chat

### Date et heure de l'apparition problème

23/09 à 15h26

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/70896724/d320a075-b0e7-4d40-bf80-25df53445c0b)

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report.
