### ISSUE TITLE
[SUGGESTION] Entonnoir de farm

### ISSUE THREAD

**Issue by LVeloute** [RemainSky/RemainSky-Issues#32]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

LVeloute

### Votre pseudo discord

velouté

### Que s'est-il passé ?

l'entonnoir de farm n'aspire pas les loot des mobs (que les fils)

### Comment reproduire le bug ?

tuer un mobs dans le meme chunk qu'un entonnoir de farm

### Qu'aurait-il dû arriver ?

aspirer le loot

### Date et heure de l'apparition problème

23/09 15:27

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/145841404/0fa529f3-00c0-4053-b1cc-c1b43aa2ecd8)

**Comment by NewZAZ** [comment]
- Ajouter les loots de mobs dans l'hopper de farm @SwartZCoding

**Comment by SwartZCoding** [comment]
> ### Confirmation
> * [x]  J'ai vérifié que le bug n'a pas déjà été signalé.
> * [x]  Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)
> 
> ### Votre pseudo en jeu
> LVeloute
> 
> ### Votre pseudo discord
> velouté
> 
> ### Que s'est-il passé ?
> l'entonnoir de farm n'aspire pas les loot des mobs (que les fils)
> 
> ### Comment reproduire le bug ?
> tuer un mobs dans le meme chunk qu'un entonnoir de farm
> 
> ### Qu'aurait-il dû arriver ?
> aspirer le loot
> 
> ### Date et heure de l'apparition problème
> 23/09 15:27
> 
> ### Serveur
> Skyblock
> 
> ### Screen / vidéo
> ![image](https://user-images.githubusercontent.com/145841404/270111202-0fa529f3-00c0-4053-b1cc-c1b43aa2ecd8.png)
> 
> ### Informations complémentaires
> _No response_

Nous avons peur que cela soit problématique pour des joueurs ayant leurs spawners dans le même chunk que des farms. Et ils ne souhaitent pas forcément avoir des loots de mobs dans ce hopper. Le problème avait déjà été soulevé lors de la saison 1.

**Comment by SwartZCoding** [comment]
Proposition : Pouvoir configurer l'activation et désactivation de ce qu'on veut que le hopper récup.

**Comment by NewZAZ** [comment]
Fini, il manque à finir la configuration, l'esthétiques et les messages
