### ISSUE TITLE
[BUG] Cuire mouton

### ISSUE THREAD

**Issue by Matthlo** [RemainSky/RemainSky-Issues#33]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Devil_Mat

### Votre pseudo discord

Devil_Mat

### Que s'est-il passé ?

Vous devriez préciser cuire de la viande de mouton aulieu de cuire mouton

### Comment reproduire le bug ?

./success

### Qu'aurait-il dû arriver ?

changer la desc

### Date et heure de l'apparition problème

23/09 à 15h33

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/70896724/a910d2c5-e906-428e-8019-cf1eed3b48bc)

**Comment by SwartZCoding** [comment]
Corrigé au prochain reboot. Merci de ton report !
