### ISSUE TITLE
[BUG] furniture_sit activé sur les fontaines

### ISSUE THREAD

**Issue by Endojoy** [RemainSky/RemainSky-Issues#34]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

EnjoyI

### Votre pseudo discord

endodoy

### Que s'est-il passé ?

Je peux m'assoir sur les fontaines au warp caisse

### Comment reproduire le bug ?

s'assoir sur les fontaines 

### Qu'aurait-il dû arriver ?

ce n'est pas vraiment ce que j'appelle un siège :) 

### Date et heure de l'apparition problème

23/09/2023 15h33

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/126188070/d8d51c71-0447-42a3-bbc0-3fb0dc2aaacf)

**Comment by NewZAZ** [comment]
ce n'est pas un bug :)
