### ISSUE TITLE
[BUG] Fautes

### ISSUE THREAD

**Issue by LegLinx** [RemainSky/RemainSky-Issues#35]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

LegLinx

### Votre pseudo discord

LegLinx

### Que s'est-il passé ?

Il y a juste trois fautes au niveau du succès Enchanteur 5/8/10, il y a un "S" à objet alors qu'il faut qu'un seul item

### Comment reproduire le bug ?

/success

### Qu'aurait-il dû arriver ?

Changer la desciption

### Date et heure de l'apparition problème

23/09/2023 à 15h40

### Serveur

Skyblock

### Screen / vidéo

![2023-09-23_15 42 12](https://github.com/RemainSky/RemainSky-Issues/assets/145851319/2baa61e9-86a3-4217-a462-80223a796816)
![2023-09-23_15 42 16](https://github.com/RemainSky/RemainSky-Issues/assets/145851319/cc55484a-769d-414f-b093-6fb990800932)
![2023-09-23_15 42 18](https://github.com/RemainSky/RemainSky-Issues/assets/145851319/032a6f75-a345-4016-97b5-72f97e4fec56)

**Comment by SwartZCoding** [comment]
Ce n'est pas une faute d'orthographe. Les succès sont nerfs. A l'ouverture ce ne sera pas un mais plusieurs objets. Merci quand même de ton report :) !
