### ISSUE TITLE
[BUG] Volcan

### ISSUE THREAD

**Issue by LVeloute** [RemainSky/RemainSky-Issues#36]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

LVeloute

### Votre pseudo discord

velouté

### Que s'est-il passé ?

dans les possibilté de gagner de l'xp dans le metier chasseur il y a parcticipar a un volcan et dans les recompense vitesse 2 et force au volcan alors qu'il n'y a plus de volcan

### Comment reproduire le bug ?

regarde les façon d'xp et les recompense du métier de chasseur

### Qu'aurait-il dû arriver ?

retirer des recompense

### Date et heure de l'apparition problème

23/09 15:43

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/145841404/d49d779e-ab53-424f-a556-87166256070d)

**Comment by SwartZCoding** [comment]
Corrigé, désormais c'est dans les mondes. Merci de ton report
