### ISSUE TITLE
[SUGGESTION] kill les golems de fer

### ISSUE THREAD

**Issue by Matthlo** [RemainSky/RemainSky-Issues#37]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Devil_Mat

### Votre pseudo discord

Devil_Mat

### Que s'est-il passé ?

Il faudrait faire en sort que les golems se fassent kill plus vite, là c'est useless d'avoir "bcp" de spawners vu qu'ils ne meurent que 1par1

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

.

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/70896724/16d0d858-2d21-40fe-8b98-c1bbb6eca22e)

### Informations complémentaires

Là par exemple on a des stack de 8k, complétement inutile

**Comment by NewZAZ** [comment]
Good
