### ISSUE TITLE
[BUG] Fautes

### ISSUE THREAD

**Issue by LegLinx** [RemainSky/RemainSky-Issues#38]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

LegLinx

### Votre pseudo discord

LegLinx

### Que s'est-il passé ?

Plusieurs fautes pour les succes Ingénieur 7/8, encore une fautes avec un "S" sur un besoin d'un item

### Comment reproduire le bug ?

/succes

### Qu'aurait-il dû arriver ?

Changer la description

### Date et heure de l'apparition problème

23/09/2023 à 15h47

### Serveur

Skyblock

### Screen / vidéo

![2023-09-23_15 45 16](https://github.com/RemainSky/RemainSky-Issues/assets/145851319/e710899c-bc80-4be0-af90-06f3a727d174)
![2023-09-23_15 45 18](https://github.com/RemainSky/RemainSky-Issues/assets/145851319/f8a08a3f-a8b9-42de-a1f4-8f7f8af9b306)

**Comment by SwartZCoding** [comment]
Ce n'est pas une faute d'orthographe. Les succès sont nerfs. A l'ouverture ce ne sera pas un mais plusieurs objets. Merci quand même de ton report :) !
