### ISSUE TITLE
[BUG] TAG

### ISSUE THREAD

**Issue by LVeloute** [RemainSky/RemainSky-Issues#39]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

LVeloute

### Votre pseudo discord

velouté

### Que s'est-il passé ?

on peut pas mettre de tag alors qu'on est lvl 20 metier

### Comment reproduire le bug ?

essaye de mettre un tag metier

### Qu'aurait-il dû arriver ?

pouvoir mettre le tag

### Date et heure de l'apparition problème

23/09 15:50

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Vous avez eu les niveaux 20 artificiellement. Donc les tags ne vous ont pas été attribués. C'est pas un bug du coup ^^.
