### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by LVeloute** [RemainSky/RemainSky-Issues#4]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

LVeloute

### Votre pseudo discord

velouté

### Que s'est-il passé ?

dans la liste des /warps on ne peut pas se tp au warps dark et au warp abandonned

### Comment reproduire le bug ?

/warp dark

### Qu'aurait-il dû arriver ?

un tp 

### Date et heure de l'apparition problème

14:18 23/09/2023

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
@LVeloute C'est normal tu n'as pas le rang nécessaire
