### ISSUE TITLE
[SUGGESTION] XP "épée du chasseur" avec le kill des champis dans la zone 

### ISSUE THREAD

**Issue by Skiniix** [RemainSky/RemainSky-Issues#40]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Skiniix

### Votre pseudo discord

Skiniix

### Que s'est-il passé ?

Le kill des champis dans la zone champis nous rapporte de l'xp métier, mais pas d'xp pour up "l'épée du chasseur".

### Comment reproduire le bug ?

Tuer des champis avec l'épée du chasseur 

### Qu'aurait-il dû arriver ?

Gagner de l'xp et métier ET de l'xp pour améliorer l'epée du chasseur 

### Date et heure de l'apparition problème

23/09/23 à 15h55

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
@SwartZCoding Intéressant de l'ajouter ?

**Comment by SwartZCoding** [comment]
> @SwartZCoding Intéressant de l'ajouter ?

Oui on peut ajouter.

**Comment by NewZAZ** [comment]
good
