### ISSUE TITLE
[BUG] /condense avec des os

### ISSUE THREAD

**Issue by Matthlo** [RemainSky/RemainSky-Issues#41]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Devil_Mat

### Votre pseudo discord

Devil_Mat

### Que s'est-il passé ?

Quand on /condense avec 9 os ça nous donne un block d'os

### Comment reproduire le bug ?

avoir 9os et /condense

### Qu'aurait-il dû arriver ?

un os = 3 bonemeal, et 9bonemeal 1blocks, donc on aurait du avoir 3 block d'os

### Date et heure de l'apparition problème

23/09 à 16h16

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report.
