### ISSUE TITLE
[BUG] Petite faute

### ISSUE THREAD

**Issue by Skiniix** [RemainSky/RemainSky-Issues#42]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Skiniix

### Votre pseudo discord

Skiniix

### Que s'est-il passé ?

"blé sacré", et non "blé sacrée". 

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

23/09/23 à 16h08

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
corrigé au prochain reboot pour les nouveaux blés mis en circulation.
