### ISSUE TITLE
drop de livre enchanté sans enchantement

### ISSUE THREAD

**Issue by corentaing10** [RemainSky/RemainSky-Issues#43]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Corentaing

### Votre pseudo discord

corentaing#8448

### Que s'est-il passé ?

j'ai peché avec la canne a peche de toumai et ca me drop des livres enchanté sans enchantement

### Comment reproduire le bug ?

Pecher avec la canne du pecheur (canne a peche de toumai)

### Qu'aurait-il dû arriver ?

soit pas m'en drop sois me drop avec des enchantements dessus

### Date et heure de l'apparition problème

23/09/23 à 16:20

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/109032525/4c25869d-32b7-493d-9884-ce080554088c)

**Comment by NewZAZ** [comment]
fix
