### ISSUE TITLE
[BUG] Pas d'xp mineur en cassant avec le "marteau"

### ISSUE THREAD

**Issue by Skiniix** [RemainSky/RemainSky-Issues#44]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Skiniix

### Votre pseudo discord

Skiniix

### Que s'est-il passé ?

En cassant des blocs qui sont censés nous donner de l'xp pour le métier de mineur, nous obtenons pas d'xp pour celui mais que de l'xp afin de up le marteau.

### Comment reproduire le bug ?

Miner avec le marteau 

### Qu'aurait-il dû arriver ?

Obtenir de l'xp pour le job mineur 

### Date et heure de l'apparition problème

23/09/23 à 16h23

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
@Skiniix tu casse quoi comme block ? car personnellement ça fonctionne bien

**Comment by Skiniix** [comment]
Ouais nan my bad, j'ai cassé de la cobble et non de la roche...
