### ISSUE TITLE
[BUG] Craft engrenage

### ISSUE THREAD

**Issue by PilBandit** [RemainSky/RemainSky-Issues#45]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Pil_Bandit

### Votre pseudo discord

Pil_Bandit

### Que s'est-il passé ?

Le craft de l'item engrenage demande 2 d'engrenages ce qui est soit une erreur soit complétement stupide...

### Comment reproduire le bug ?

regarder la recette de l'engrenage

### Qu'aurait-il dû arriver ?

Aucune idée

### Date et heure de l'apparition problème

23/09/2023 à 16h30

### Serveur

Skyblock

### Screen / vidéo

https://i.badlion.net/jPdbc57F6gzTsjqNA9uXdE.png

**Comment by SwartZCoding** [comment]
Ton launcher est bug. Les launchers ne peuvent pas donner correctement les crafts des items customs.

C'est des fragments de pépite de volca à la place. L'ensemble des crafts seront disponibles sur le wiki à l'ouverture.

Merci de ton report.
