### ISSUE TITLE
[BUG] Volcan présent sur la carte

### ISSUE THREAD

**Issue by PilBandit** [RemainSky/RemainSky-Issues#46]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Pil_Bandit

### Votre pseudo discord

Pil_Bandit

### Que s'est-il passé ?

Sur la carte du spawn, le volcan est disponible alors que lorsque l'on y va le volcan n'existe pas

### Comment reproduire le bug ?

Allez a la carte et se rendre au niveau du lieu du volcan

### Qu'aurait-il dû arriver ?

Enlever le point de la carte

### Date et heure de l'apparition problème

23/09/2023 à 16h45

### Serveur

Skyblock

### Screen / vidéo

https://i.badlion.net/q3n8Z2hXA69t454DHRzKM9.png
https://i.badlion.net/5CHPPx8Rf7PhFXCYm5c2Tc.png

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report.
