### ISSUE TITLE
[BUG] Pourcentage rune

### ISSUE THREAD

**Issue by Matthlo** [RemainSky/RemainSky-Issues#47]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Devil_Mat

### Votre pseudo discord

Devil_Mat

### Que s'est-il passé ?

revoir les pourcentages écrit sur les runes

### Comment reproduire le bug ?

t

### Qu'aurait-il dû arriver ?

t

### Date et heure de l'apparition problème

t

### Serveur

Skyblock

### Screen / vidéo

t

### Informations complémentaires

vu en voc, mettre les mêmes pourcentages que dans la config et préciser que le 5*5 a un pourcentage

**Comment by SwartZCoding** [comment]
Corrigé au prochain reboot ! Merci de ton report.
