### ISSUE TITLE
[BUG] bouton sell all sac agriculture

### ISSUE THREAD

**Issue by Matthlo** [RemainSky/RemainSky-Issues#48]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Devil_Mat

### Votre pseudo discord

Devil_Mat

### Que s'est-il passé ?

le bouton sell all ne fonctionne pas

### Comment reproduire le bug ?

prendre un sac, et essayer de sell

### Qu'aurait-il dû arriver ?

vendre les items

### Date et heure de l'apparition problème

23/09 à 17h17

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/70896724/4702c9d1-db38-4857-907e-bf38b97d6fad)
![image](https://github.com/RemainSky/RemainSky-Issues/assets/70896724/980ad49d-ae55-4787-8682-5fa95b00cd69)

**Comment by NewZAZ** [comment]
fix
