### ISSUE TITLE
[BUG] Fautes d'orthographes en générale

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#49]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

**Problèmes d'orthographes :**

pnj caverne au /is go → "a échanger" → "à échanger"
Hâche à melons → problème de lower "%rune" + "Hache" accent circonflexe
Hâche à citrouilles → problème de lower "%rune%" + "Hache" accent circonflexe à enlever
Hâche à cacao → "Hache" accent circonflexe à enlever + mes un "s" à "Cacao"
Hâche du Bucheron → "Hache du Bûcheron"
Hâche Sacrée → Hache Sacrée + modifier dans les lowers "Cette hâche" → "Cette hache"
Houe à Blé → Houe à Blés
Planteur → "vos graine"  → "vos graines"
/shop, il est écrit partout "magagin" au lieu de magasin
/shop, il est écrit "Cliquez gauche/Cliquez Droit" c'est mieux de mettre "Clic gauche/Clic Droit" c'est plus français
dans la foreuse "Récupérez vos ressources généré par votre foreuse" → "vos ressources générées"
description du RemainsBag "Tenez votre chance" → "Tentez votre chance"

**Job Mineur Récompenses :**
"Doubler ces minerais" → "Doubler ses minerais"
Niveau 5 → "sur le vente" → "sur la vente"

**Job Agriculteur Récompenses :**
"Doubler ces récoltes" → "Doubler ses récoltes"
Niveau 10 → "Déblocage de la hâche à citrouilles" → "Déblocage de la hache à citrouilles"
Niveau 15 → "Déblocage de la hâche à pastèques" → "Déblocage de la hache à pastèques"

**Job Menuisier Récompenses :**
Niveau 3 → "Une clée rare" → "Une clé rare"
Niveau 10 → "... la tâble du menuisier." → "...la table du menuisier"
Niveau 17 et 20 → "Une clée épique" → "Une clé épique"

**Job Ingénieur Récompenses :**
Niveau 15 → "tâble du menuisier" → "table du menuisier"

**Job Enchanteur Récompenses :**
Niveau 10 → "de la tâble d'enchantement" → "de la table d'enchantement"
Niveau 17 → "Une clée épique" → "Une clé épique"

Menu /jobs → "Pécheur" → "Pêcheur" 

**Menu is upgrade :**

Hopper → remplacer par "Entonnoir" car tout est en français
Taille de l'île → "Améliorez la taille maximum" → "Améliorez la taille maximale"
Limites de membres → "Améliorez la limite de membre de votre île et invité plus de membre" → "Améliorez la limite de membres de votre île et invitez plus de membres"

**Tutoriel dans le chat :**
"Vous voulez en apprendre d'avantage" → "Vous voulez en apprendre davantage"

Tous les pnjs du spawn + caisses :
"Clique droit" → "Clic droit"
Toumai → "Vous n'avez pas l'argent nécéssaires" → "Vous n'avez pas l'argent nécessaire"

**Monde champi :**
"un monde rempli" → "un monde remplit"
"à l'apparence gentils" → "à l'apparence gentille"

**Monde Ténébreux :**
"Découvrez un monde dangereux rempli de gobelins féroce" → "Découvrez un monde dangereux remplit de gobelins féroces"

dans le /aide → Profil → la description n'est pas la bonne + la commande non fonctionnelle = /profile SamaZz_ pour que ça fonctionne

au /warp mine → Le pnj → "Sinon tu ne t'en sortira pas" → "Sinon tu ne t'en sortiras pas"
au /warp echange → Hologramme "d'd'or" → "d'or"
au /warp taverne → Le pnj → "des décorations incroyable" → "des décorations incroyables"

**Succès :**

Mineur #8 : "2 débris ancien" → "2 débris anciens"
Menuisier #9 : "tâble du charpentier" → "table du menuisier"
Pécheur → Pêcheur (titre + description) #5 : "Pêcher 2 poisson-globe" → "Pêcher 2 poissons-globes"
Enchanteur #3 et #10 : "1 tâble d'enchantement" → "1 table d'enchantement"

**Table du menuisier :**
Tâble → Table
Puits → Puit

**Renforceur :**
Le contour est remplis du menu Job Pêcheur

**Events :**
Guerre d'île : "Tous les Samedi" → "Tous les Samedis"
 

### Comment reproduire le bug ?

Les corriger

### Qu'aurait-il dû arriver ?

Une correction.

### Date et heure de l'apparition problème

23/09/2023

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Tous sera fix au prochain reboot. Merci du report.
