### ISSUE TITLE
[BUG] commande inconnue /is tops

### ISSUE THREAD

**Issue by Matthlo** [RemainSky/RemainSky-Issues#5]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Devil_Mat

### Votre pseudo discord

Devil_Mat

### Que s'est-il passé ?

Quand je fait /is et clique sur classement j'ai commande inconnue

### Comment reproduire le bug ?

./is -> cliquer sur classement

### Qu'aurait-il dû arriver ?

ouvrir le classement

### Date et heure de l'apparition problème

23/09 à 14h22

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/70896724/00f4f22b-b041-4efa-b853-86147c83ae1a)

**Comment by SwartZCoding** [comment]
Corrigé au prochain reboot. Merci pour le report.
