### ISSUE TITLE
[BUG] Commandes

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#50]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

**Les commandes non fonctionnelles :**

./furnace
./unfire

### Comment reproduire le bug ?

./furnace
./unfire

### Qu'aurait-il dû arriver ?

un bon fonctionnement de commande.

### Date et heure de l'apparition problème

23/09/2023

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/145837411/212a0f40-34e2-4a2b-96ea-59ed64a7bbd6)

**Comment by NewZAZ** [comment]
good
