### ISSUE TITLE
Item netherite

### ISSUE THREAD

**Issue by corentaing10** [RemainSky/RemainSky-Issues#51]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Corentaing

### Votre pseudo discord

corentaing#8448

### Que s'est-il passé ?

il manque le smithing template (motif de forge) pour mettre un item en netherite et on peux en aucun cas en avoir 

### Comment reproduire le bug ?

ouvrir une smiting table

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

23/09/23 à 17:50

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/109032525/cf926667-13d5-4139-b846-415db63aba86)

**Comment by corentaing10** [comment]
Ce qu'il faux pour faire les items en Netherite


![image](https://github.com/RemainSky/RemainSky-Issues/assets/109032525/e752efe9-2063-4f52-b739-7e46b1974e20)

**Comment by NewZAZ** [comment]
Fix j'ai ajouter au shop
