### ISSUE TITLE
[BUG] Hache Cacao Niveau 3

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#52]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Hache Cacao ne casse pas en 3x3 et met pas les récolte dans le backpack agriculture

### Comment reproduire le bug ?

farm le cacao

### Qu'aurait-il dû arriver ?

Le cacao soit cassé sur une zone 3x3 et soit mis dans le backpack

### Date et heure de l'apparition problème

23/09

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
En aucun cas c'est écris que ça casse du 3x3, ça drop juste plus et replante. Et pour le backpack c'est fix
