### ISSUE TITLE
[BUG] Vente pour le gain d'xp job

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#53]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

en faisant /sell all ou bien même en vendant au /shop, on ne gagne pas d'xp job quelque soit l'item vendu du job.

### Comment reproduire le bug ?

vendre des items quelconques

### Qu'aurait-il dû arriver ?

Gain d'xp lors d'une vente d'item précisez dans un job.

### Date et heure de l'apparition problème

23/09

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
fix
