### ISSUE TITLE
[BUG] Orthographe du /ah

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#55]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Catégorie Arme → Catégorie Armes
Informations → Nombres d'objets disponible: 2 → disponibles

### Comment reproduire le bug ?

/ah

### Qu'aurait-il dû arriver ?

Corriger les fautes

### Date et heure de l'apparition problème

23/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Fix. Merci du report.
