### ISSUE TITLE
[SUGGESTION] Job + Farm + BackPack

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#56]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

**L'idée serait que toutes les cultures farmables aux outils spéciaux soient vendable en sacrée aussi telles que :**
- Netherwart
- Sweet Berries
- Cacaos
- Tranches de melon
- Pumpkin

**BackPack :**
- Rajouter la récolte des patates empoisonnées
- Rajouter la récolte de tous les agricultures sacrées

**Job agriculteur :**
- Rajouter un gain d'xp plus élevé quand on vend des cultures sacrées

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

23/09

### Serveur

Skyblock

**Comment by S4maZz** [comment]
Rajouter un gain d'xp métier sur la vente de la canne à sucre métier agriculteur

**Comment by SwartZCoding** [comment]
Gain d'XP amélioré.
Ajout des plantations sacrées good.

Le reste non accepté.
