### ISSUE TITLE
[BUG] Is biomes / Warp d'île / permissions d'îles

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#57]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

**Biomes Overworld :**
- "Biome - Taiga" → Biome - Taïga + description = "Changez le biome de votre île en taiga" → ".... taïga"
- "Biome - Sunflower Plains" → "Biome - Plaine de tournesols" + description = "Changez le biome de votre île en Sunflower Plains" → "... plaine de tournesols"
- "Biome - Désert" → description = "Changez le biome de votre île en desert" → "... désert"
- "Biome - Foret" → "Biome - Forêt" + description = "Changez le biome de votre en Foret" → "... forêt"
- "Biome - Jungle Bamboo" → "Biome - Jungle de Bambous" + description = "Changez le biome de votre en Jungle Bamboo" → "... Jungle de bambous"

**Création de warp :**
- Création de warp : "Nouveau warp crée au coordonnées ..." → "Nouveau warp créé aux coordonnées ..."
- Désactiver la commande /is fly = fly gratuit :slight_smile:

**Is permissions :**

- Utiliser des EnderPearl → Utiliser des Enderpearls
- Sauter les récoltes → "... en sautant sur ces dernieres" → "... sur ces dernières"
- Peinture → "Pouvoir interagir" → "Pouvoir intéragir"
- Promouvoir des membres → "... des membres au sain" → "... au sein"
- Pancarte → "Pouvoir interagir" → "Pouvoir intéragir"

./is help 7 → /is transfer "Transferer la direction..." → "Transférer la direction.."

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

23/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé merci de ton report !
