### ISSUE TITLE
temps des missions des mondes

### ISSUE THREAD

**Issue by corentaing10** [RemainSky/RemainSky-Issues#58]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Corentaing

### Votre pseudo discord

corentaing#8448

### Que s'est-il passé ?

j'ai eu un defi sur le monde champi et ca m'a lancé a 30s au lieu de 2 minutes annoncé

### Comment reproduire le bug ?

on restant un peu dans le monde champi

### Qu'aurait-il dû arriver ?

Etre a 2 minutes au lieu de 30s

### Date et heure de l'apparition problème

23/09/23 à 21:55

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/109032525/75aa4a1c-725c-491a-bc49-2f5f88f9b049)

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report.
