### ISSUE TITLE
Craft Crying obsi

### ISSUE THREAD

**Issue by corentaing10** [RemainSky/RemainSky-Issues#59]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Corentaing

### Votre pseudo discord

corentaing#8448

### Que s'est-il passé ?

on peux pas crafter les crying obsi car on a pas la perm

### Comment reproduire le bug ?

faire le craft (montré sur l'image plus tard)

### Qu'aurait-il dû arriver ?

le craft

### Date et heure de l'apparition problème

24/09/23 à 1:00

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/109032525/eafaa9e5-814a-4c81-a1d0-2e8c124d1ed9)

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report.
