### ISSUE TITLE
[BUG] Epée ultime

### ISSUE THREAD

**Issue by Elrinne** [RemainSky/RemainSky-Issues#6]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Elrinne

### Votre pseudo discord

Elrinne

### Que s'est-il passé ?

L'épée ultime perd de la durabilité quand on l'utilise

### Comment reproduire le bug ?

taper avec l'épée ultime sur un mob passif/aggressif

### Qu'aurait-il dû arriver ?

l'epée ne devrait pas perdre de dura

### Date et heure de l'apparition problème

23/09/2023 à 14:24

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Pas un bug. C'est pas un objet de toumai.
