### ISSUE TITLE
[BUG] Gain d'xp Explorateur

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#60]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Quand j'ai ouvert une clé vote, je n'ai pas reçu l'xp de l'explorateur.

### Comment reproduire le bug ?

ouvrir une clé vote.

### Qu'aurait-il dû arriver ?

Gagner l'xp

### Date et heure de l'apparition problème

24/09

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
Fix
