### ISSUE TITLE
[ORTHOGRAPHE] Différentes tables modées + Caverne des pouvoirs

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#61]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

**Le Catalyseur :**
- description : "cette tâble" → "cette table" et la bonne description serait → "Posez cette table et transformez vos cultures !"
- Le nom de l'item n'est pas en couleur.

**Table d'enchantement améliorée :**
- description : "cette tâble" → "cette table"

**Tâble du Menuisier :** → Table du Menuisier (Nom item)
- description : "cette tâble" → "cette table"

**Caverne de pouvoirs :**
- Dans le chat ça écrit → "Caserne des pouvoirs - Vous avez ajouté x points à votre caserne !" → "Caverne de pouvoirs - "... à votre caverne"

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

24/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé au prochain reboot. Merci de ton report.
