### ISSUE TITLE
Blé sacré

### ISSUE THREAD

**Issue by NatonatTroBo** [RemainSky/RemainSky-Issues#62]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Natonat

### Votre pseudo discord

natonat

### Que s'est-il passé ?

Le blé sacré ne se vends pas au /shop ni au /sell all alors que ça le faisais hier

### Comment reproduire le bug ?

essayer de vendre du blé sacré

### Qu'aurait-il dû arriver ?

Qu'il soit vendu

### Date et heure de l'apparition problème

24/09/2023 à 10h15

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report.
