### ISSUE TITLE
Pastèque

### ISSUE THREAD

**Issue by NatonatTroBo** [RemainSky/RemainSky-Issues#63]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Natonat

### Votre pseudo discord

natonat

### Que s'est-il passé ?

Les blocs de pastèques se vendent 1$ et les part de pastèque de même

### Comment reproduire le bug ?

Faire /shop

### Qu'aurait-il dû arriver ?

Que les parts soient moins cher

### Date et heure de l'apparition problème

24/09/2023 à 10h15

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé ! merci de ton report.
