### ISSUE TITLE
[ORTHOGRAPHE] Comandes

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#64]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

./unfire → " d''éteindre" → d'éteindre

**Suggestion :**
./furnace all → Le cooldown est trop long
./condense → Pouvoir condense le Raw Gold, Raw Iron, Raw Copper

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

24/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report.
