### ISSUE TITLE
[ORTHOGRAPHE + SUGGESTION] Caverne de pouvoirs

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#65]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

**Boost Catalyseur :**
- "Pseudo a acheté le pouvoir boost_catalyst" → "Pseudo a acheté le pouvoir Boost du catalyseur"
- Indiqué dans la description que le pouvoir dure 1h.

**Boost d'expérience d'objets :**
- "Pseudo a acheté le pouvoir boost_custom_item_xp !" → "Pseudo a acheté le pouvoir Boost d'expérience d'objets"
- Indiqué dans la description que le pouvoir dure 30min car il dure 30min (ou 1h si c'est une erreur).

**Boost Explorateur :**
- "Pseudo a acheté le pouvoir boost_exploration !" → "Pseudo a acheté le pouvoir Boost Explorateur"

**Gain de point d'île :**
- Grâce aux cultures sacrées, on pourrait gagner aussi des points pour pouvoir acheter des pouvoirs.

!!! Ne pas oublier de changer le "Caserne" en "Caverne" à chaque achat de boost / gain de point !!!

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

24/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé ! merci de ton report.
