### ISSUE TITLE
[BUG] Monde Champi

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#66]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Le temps donné pour tuer 20 Champis est de 4min sauf qu'on en a que 2min.
Au bout d'un certain moment des zoglins spawn et se stack à la place de champis quand on les tue.

### Comment reproduire le bug ?

Tuer des champis

### Qu'aurait-il dû arriver ?

Avoir des champis au lieu d'avoir des zoglins

### Date et heure de l'apparition problème

24/09

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/145837411/df4ba7fc-4497-4087-b4ce-b679da0c67ca)

**Comment by S4maZz** [comment]
![image](https://github.com/RemainSky/RemainSky-Issues/assets/145837411/109831f9-d47f-4a7e-8126-04d34d75e07e)
Orthographe à la fin quand on sort du monde → "2 minute" → "2 minutes"

**Comment by SwartZCoding** [comment]
Je n'ai pas trouvé comment régler le souci à 100% mais j'ai réussi à atténuer son effet après plusieurs minutes de farm.
