### ISSUE TITLE
[BUG] le /ss ne fonctionne pas avec le grade modo (a tester avec les autres staffs)

### ISSUE THREAD

**Issue by Elrinne** [RemainSky/RemainSky-Issues#67]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Elrinne

### Votre pseudo discord

Elrinne

### Que s'est-il passé ?

/ss pseudo ne fonctionne pas cela 

### Comment reproduire le bug ?

/ss Pseudo

### Qu'aurait-il dû arriver ?

une interface pour les sanctions aurait du s'ouvrir

### Date et heure de l'apparition problème

24/09/2023

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/145842897/c00c4810-6765-48bc-bbc2-e34d2136ba65)

**Comment by NewZAZ** [comment]
Fix !
