### ISSUE TITLE
[BUG] mauvais equilibrage dans les monde explo

### ISSUE THREAD

**Issue by Elrinne** [RemainSky/RemainSky-Issues#68]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Elrinne

### Votre pseudo discord

Elrinne

### Que s'est-il passé ?

avec l'épée ultime je 2 shote les mobs du monde tenebreux (le derniere monde d'explo) et ceux de la mine abandonnee
donc le monde 2 est plus dur que le monde 3

### Comment reproduire le bug ?

taper les mob monde explo 2 et 3

### Qu'aurait-il dû arriver ?

la zone 2 devrait etre plus facile que la zone 3 et c'est l'inverse

### Date et heure de l'apparition problème

24/09/2023

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrige ! Merci de ton report.
