### ISSUE TITLE
[BUG] Le spawner a vache du spawn ne fonctionne pas

### ISSUE THREAD

**Issue by Elrinne** [RemainSky/RemainSky-Issues#69]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Elrinne

### Votre pseudo discord

Elrinne

### Que s'est-il passé ?

aucune vache ne pop dans la zone animaux du /spawn
alors que les cochons et moutons oui

### Comment reproduire le bug ?

patientez proche du spawner a vache du spawn

### Qu'aurait-il dû arriver ?

des vaches devraient pop

### Date et heure de l'apparition problème

24/09/2023

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
![image](https://github.com/RemainSky/RemainSky-Issues/assets/39431572/95fc66a4-d1ec-4cbd-842d-8dfa60ace708)
Après test, ca spawn bien.
