### ISSUE TITLE
[BUG] /sell all gain d'xp

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#70]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

- on gagne pas d'xp chasseur en vendant des loots de mobs.
- on gagne pas d'xp mineur en vendant des minerais.
- on gagne pas d'xp pêcheur en vendant des poissons

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

24/09

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
fix prochain redem
