### ISSUE TITLE
[BUG] Caisse Rare

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#71]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Dans le chat ça écrit un message non traduit (voir screen) quand on obtient une Pépite de Volcanite.

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

24/09

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/145837411/2e6000af-74bd-47dd-a54d-d7e60d1b1221)

**Comment by SwartZCoding** [comment]
A test au prochain reboot. Merci de ton report.

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report.
