### ISSUE TITLE
[BUG] Les legendaires sont tout en bas dans le tab

### ISSUE THREAD

**Issue by Elrinne** [RemainSky/RemainSky-Issues#72]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Elrinne

### Votre pseudo discord

Elrinne

### Que s'est-il passé ?

les joueurs avec  le grades légendaire sont au fond du tab

### Comment reproduire le bug ?

appuyer sur tab

### Qu'aurait-il dû arriver ?

il ne devrait pas être en dernier

### Date et heure de l'apparition problème

24/09/2023

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report.
