### ISSUE TITLE
[BUG] /vanish pour les modo

### ISSUE THREAD

**Issue by Elrinne** [RemainSky/RemainSky-Issues#73]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Elrinne

### Votre pseudo discord

Elrinne

### Que s'est-il passé ?

lorsque je fait /vanish cela me dit que je n'ai pas les perm
alors que ça marche avec le /staff

### Comment reproduire le bug ?

/vanish en etant modo

### Qu'aurait-il dû arriver ?

j'aurais du pouvoir etre mise en vansih

### Date et heure de l'apparition problème

24/09/2023

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report.
