### ISSUE TITLE
[BUG] Nom du modo dans le chat  en bleu

### ISSUE THREAD

**Issue by Elrinne** [RemainSky/RemainSky-Issues#74]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Elrinne

### Votre pseudo discord

Elrinne

### Que s'est-il passé ?

Pseudo des modo en bleu au lieu de violet

normal que l'ecriture soit en blanc pour les modo et les guides? (les guides ecrivait en vert en V1)

### Comment reproduire le bug ?

ecrite dans le chat pour un modo / guide

### Qu'aurait-il dû arriver ?

une autre couleur

### Date et heure de l'apparition problème

24/09/2023

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report.
