### ISSUE TITLE
[ORTHOGRAPHE] Les Atouts

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#75]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Quand on active les atouts ça écrit en anglais et parfois mal :

**Atouts :**
- "Votre atout de haste est maintenant activé" → "Votre atout de célérité...."
- "Votre atout de speed est maintenant activé" → "Votre atout de vitesse...."
- "Votre atout de glowing est maintenant activé" → "Votre atout de surbrillance...."
- "Votre atout de fire_resistance est maintenant activé" → "Votre atout de résistance au feu...."

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

24/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
@NewZAZ Il faut que tu ajoute un champ pour permettre un nom d'affichage.

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report !
