### ISSUE TITLE
[SUGGESTION] Concernant le farm avec le backpack

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#76]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Concernant le cooldown sur le backpack pour sell all je trouve ça inutile je m'explique :

Quand le backpack est amélioré au max, il permet de stocker que 10 000 items ce qui est déjà premièrement très peu car on farm cette quantité en moins de 5 minutes très clairement quelque soit le champ.
Cependant, vous me direz il y a certe le sell all, sauf qu'il faut vider tout son backpack puis /sell all toutes les cultures à terre ? Ca devient chiant à faire au bout d'un moment.
Puis quand on farm, le backpack est le seul moyen de récupérer directement les items dans un inventaire car si on ne le possède pas, les cultures tombent à terre et rendent donc /sell all "inutile" si on peut dire ça.

Donc pour moi il faudrait augmenter la capacité du backpack ainsi que retirer son cooldown.

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

24/09

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
@SwartZCoding

**Comment by SwartZCoding** [comment]
Multiplication par 10 de la récolte.
