### ISSUE TITLE
Metier explorateur

### ISSUE THREAD

**Issue by corentaing10** [RemainSky/RemainSky-Issues#77]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Corentaing

### Votre pseudo discord

corentaing#8448

### Que s'est-il passé ?

j'ai 35k% dans mon metier explorateur (screen a l'appui)

### Comment reproduire le bug ?

juste en jetant des items dans le puit

### Qu'aurait-il dû arriver ?

ne pas avoir un si gros pourcentage

### Date et heure de l'apparition problème

24/09/23 à 12:22

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/109032525/365eca04-0bc8-4f40-967d-ea52052116fd)
![image](https://github.com/RemainSky/RemainSky-Issues/assets/109032525/50040d9b-9d92-422b-b1df-8398cb1d262e)

**Comment by SwartZCoding** [comment]
C'est juste que l'xp a été multiplié par x1000 pour la bêta. Ce n'est pas un bug. Merci de ton report.
