### ISSUE TITLE
[SUGGESTION] Les mobs passifs

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#78]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Pouvoir kill un stack de mob en 1 coup avec par exemple les dégâts de chute / lave / cactus / magma block / camp fire...

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

24/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Beaucoup trop cheat. Ce ne sera pas appliqué. Merci quand même pour la suggestion !
