### ISSUE TITLE
[BUG] Shop d'île (coffres)

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#79]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

On n'a pas la permission de changer un prix d'une boutique de vente/achat.

### Comment reproduire le bug ?

Créer un shop et faire /qs price

### Qu'aurait-il dû arriver ?

la boutique change de prix.

### Date et heure de l'apparition problème

24/09

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/145837411/3c30ac4e-291c-4b76-b1af-a8ea8c8bc09a)

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report.
