### ISSUE TITLE
[BUG] Les champs ne nous font pas de dégâts dans la zone 

### ISSUE THREAD

**Issue by Skiniix** [RemainSky/RemainSky-Issues#8]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Skiniix

### Votre pseudo discord

Skiniix

### Que s'est-il passé ?

Pas de dégâts de la part des champignons dans la zone 

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

Prendre des dégâts 

### Date et heure de l'apparition problème

23/09/23 à 14h25

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
@Skiniix Dans la zone du spawn ou en dehors ?

**Comment by Skiniix** [comment]
Toute la zone @NewZAZ

**Comment by SwartZCoding** [comment]
Corrigé ! Merci du report.
