### ISSUE TITLE
[ORTHOGRAPHE] 

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#80]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Explosion de Creeper → "aux creeper" → "aux creepers"
Animaux naturel → Animaux naturels → "le spawn des animaux naturel" → "le spawn des animaux naturels"
Monstres naturel → Monstres naturels → "le spawn des des monstres naturel" → "le spawn des monstres naturels"
Explosion de TNT → "Permettez au TNT..." → "Permettre aux TNT..."
Explosion de Wither → "Permettez au wither..." → "Permettre aux withers..."

Remplacer tous les "Permettez" par "Permettre" + "Laissez" par "Laisser" + "Définissez" par "Définir" + "Etablissez" par "Etablir"

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

24/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé. Merci de ton report.
