### ISSUE TITLE
[BUG] Xp éxplorateur

### ISSUE THREAD

**Issue by Skiniix** [RemainSky/RemainSky-Issues#81]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Skiniix

### Votre pseudo discord

Skiniix

### Que s'est-il passé ?

Un d'obsi dans le puit (pour xp éplorateur) = un niveau d'explorateur. 

### Comment reproduire le bug ?

Jetter un par un des blocs d'obsi dans le puit 

### Qu'aurait-il dû arriver ?

Ne pas obtenir autant d'xp

### Date et heure de l'apparition problème

24/09/23 à 14h23

### Serveur

Skyblock

**Comment by S4maZz** [comment]
Ce n'est pas un bug pour la 3ème fois c'est juste que le puit a été boost *1000 pour permettre de passer les niveaux plus facilement ainsi que de test les /rang

**Comment by Skiniix** [comment]
Sorry ^^
