### ISSUE TITLE
[SUGGESTION] Récompenses Jobs

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#82]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Comme de nouveaux items sont apparus, il faudrait rajouter dans les récompenses jobs quand est-ce qu'on les débloque :

- Niveau 7 : Pioche du Mineur
- Niveau 5 : Hache du bûcheron
- Niveau 7 : Canne à pêche
- Niveau 6 : Hache à Cacaos

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

24/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report.
