### ISSUE TITLE
bug serveur

### ISSUE THREAD

**Issue by corentaing10** [RemainSky/RemainSky-Issues#83]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

Corentaing

### Votre pseudo discord

corentaing#8448

### Que s'est-il passé ?

le serveur rollback assez souvent et donc presque impossible de faire ce qu'on veux 

### Comment reproduire le bug ?

ca le fait automatiquement

### Qu'aurait-il dû arriver ?

rien 

### Date et heure de l'apparition problème

24/09/23 à 15:54

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Aucun rollback. Juste des petites chutes de TPS. C'est normal nous ne sommes pas sur la machine de l'ouverture.
