### ISSUE TITLE
[BUG] Marteau + Hache Cacao + Hache Melon + Gain d'xp vente Agriculteur

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#84]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

- Quand on pose 1 bloc (peu importe lequel) on gagne 8 d'xp sur le marteau et on peut farm l'xp du marteau en faisant du poser/casser.

- La Hache Cacaos au level 1 donne entre 6-9 par cacaos ce qui n'est clairement pas normal (à voir si c'est le fait qu'on ait le double drop + fortune) je ne sais pas.

- La Hache Melon quand elle revend, elle donne bien l'xp quand on casse le block de melon mais la vente n'est pas bonne, car quand on farm, on vend des tranches sauf que ça compte comme si que ça vendait un bloc de pumpkin → 0.23xp (0.15 en la cassant + 0.08xp en vendant) pour le farm de pumpkin et 0.23xp pour le farm de melon sauf que la tranche à l'unité est à 0.04xp + 0.15xp quand on casse.

- De plus y'a un problème de base avec le gain d'xp sur l'agriculteur → 3 carottes vendues au /sell all rapporte que 0.06xp alors que c'est 0.18 normalement pareil pour la pastèque j'en vends 7 donc 0.28xp mais ça me compte que pour 1 donc 0.04xp.

**BackPack Agriculture :**
- Je viens de vendre 608 netherwarts ce qui fait normalement 42,56xp mais j'ai reçu que 0.07xp donc à corriger sur le backpack.

### Comment reproduire le bug ?

Poser un bloc et le casser au marteau

### Qu'aurait-il dû arriver ?

Aucun gain d'xp

### Date et heure de l'apparition problème

25/09

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
fix prochain redem
