### ISSUE TITLE
[BUG] Cisaille Améliorée

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#86]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Suite à de nombreux test sur 200 baies environs, je constate que le double drop ne fonctionne pas sur les baies mais que les 20% sont bien fonctionnels car on gagne entre 2-4 baies par clic droit.

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

26/09

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
fix prochain redem !
