### ISSUE TITLE
[BUG GRAPHIQUE] GUI BackPack Agriculture

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#87]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Voir screen ci-dessous :

Les cultures sont pas cadrés dans leur cases du pack contrairement aux items du backpack mineur

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

26/09

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/145837411/f0b96b01-1b43-433f-9039-1ef4c6919810)
![image](https://github.com/RemainSky/RemainSky-Issues/assets/145837411/7df71e5b-22c6-4d32-a07f-832aa28c2439)

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report.
