### ISSUE TITLE
[BUG + SUGGESTION + ORTHOGRAPHE] Runes sur les items légendaires

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#88]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

**La Rune Récolte d'écailles :**

- Sur la Hache citrouille, la rune ne fonctionne pas elle drop 0 écailles mais sur toutes les houes elle fonctionne.
- Parcontre sur la Hache melon, la rune fonctionne très bien.

- Ajouter sur la table du Renforceur qu'on est limité qu'à 2 runes max par items

- Ajouter la possibilité de mettre les runes suivantes sur la cisaille Améliorée : **Récolte d'écailles, Restauration, Richesse, Transformation de Plantation**

- Problème d'orthographe (écrit en anglais au lieu de français) : "Restoration" → "Restauration"

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

26/09

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/145837411/e9097078-4854-4d14-940f-d66096e40525)

**Comment by SwartZCoding** [comment]
Faute corrigée
