### ISSUE TITLE
[SUGGESTION] Planteur

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#89]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Rajouter la possibilité de planter du cacao avec le planteur sans que la bûche soit écorcée à cause du planteur qui est une hache.

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

26/09

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
@SwartZCoding tu en pense quoi ?

**Comment by NewZAZ** [comment]
La suggestion n'a pas été pris en compte, mais nous avons cancel l'action d'écorçage
