### ISSUE TITLE
[BUG] PUIT

### ISSUE THREAD

**Issue by LVeloute** [RemainSky/RemainSky-Issues#9]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

LVeloute

### Votre pseudo discord

velouté

### Que s'est-il passé ?

quand je jette un block d'or dans le puit il ne se passe rien et je ne gagne pas d'xp

### Comment reproduire le bug ?

jeter un bloc d'or dans le puit

### Qu'aurait-il dû arriver ?

gagner de l'xp explorateur

### Date et heure de l'apparition problème

14h29 23/09

### Serveur

Skyblock

**Comment by Matthlo** [comment]
je me permet d'ajouter qu'aucun item ne fonctionne

**Comment by NewZAZ** [comment]
Fix prochain redémarrage

**Comment by corentaing10** [comment]
> Fix prochain redémarrage

le bug n'est toujours pas reglé meme après le redemarrage

**Comment by NewZAZ** [comment]
fix
