### ISSUE TITLE
[SUGGESTION] Ajouter des Ascenseurs

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#90]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Le but des ascenseurs pourraient permettre aux joueurs d'accéder à des platformes sans avoir de fly ou bien même c'est très utile pour accéder à ses champs et de les farm.

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

26/09

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
@SwartZCoding Bonne idée
