### ISSUE TITLE
[ORTHOGRAPHE] Warp Tutoriel

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#91]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

d'avantage → davantage (voir screen) c'est l'hologramme
d'avantage → davantage (voir screen) c'est le pnj "Tutoriel"

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

26/09

### Serveur

Skyblock

### Screen / vidéo

![image](https://github.com/RemainSky/RemainSky-Issues/assets/145837411/f96d81d4-021b-43bc-8e99-83e3570a3b30)
![image](https://github.com/RemainSky/RemainSky-Issues/assets/145837411/4e381ee6-c817-4d29-bbb9-19d8149f9ce7)

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report.
