### ISSUE TITLE
[ORTHOGRAPHE] BackPack

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#92]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

Quand on essaie de vendre avec rien dans notre sac → "Vous n'avez pas suffisamment d'objet" → "... suffisamment d'objets"

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé !
