### ISSUE TITLE
[SUGGESTION] /box

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#93]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

rajouter un bouton dans le /box qui permet de tout récupérer directement mais il vérifie qu'on a bien la place dans l'inventaire pour tout récupérer.

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Shift + Click fonctionne.
