### ISSUE TITLE
[BUG] /protect et /2fa

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#95]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

le /protect ne fonctionne pas et le /2fa non plus → "Vous n'avez pas la permission de faire ceci."

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report.
