### ISSUE TITLE
[BUG] Rune Replantation 

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#96]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

- Quand cette rune est appliquée sur une hache melon/citrouille, quand on farm avec, ça ne repop pas comme les cultures par exemple.
- Replante bien la culture par moment mais justement, avant qu'elle ne réapparaisse on la casse donc bien 1 fois et sur cette première casse les cultures ne drop pas c'est seulement que quand on la casse une deuxième fois que ça drop.

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by NewZAZ** [comment]
fix
