### ISSUE TITLE
[ORTHOGRAPHE] les box (voir les gains clic gauche)

### ISSUE THREAD

**Issue by S4maZz** [RemainSky/RemainSky-Issues#99]
### Confirmation

- [X] J'ai vérifié que le bug n'a pas déjà été signalé.
- [X] Le bug que je signale n'est pas lié à la duplication (Ticket discord pour cela)

### Votre pseudo en jeu

SamaZz_

### Votre pseudo discord

SamaZz_

### Que s'est-il passé ?

**Box vote (Clic gauche voir les gains) :**
- "16 Sâbles des âmes" → "16 Sables des âmes"
- "Livre Raccomodage (x1)" → "Livre Raccommodage (x1)"
- "Boite aux lettres" → "Boîte aux lettres"
- "1 Shulker Vert (x1)" → "Shulker Verte (x1)"

**Box Quête :**
- "Livre Raccomodage (x1)" → "Livre Raccommodage (x1)"

**Box Cosmétique :**
- Casque de Viking → "Déguisez-vous avec ce superbe Chapeau de Viking" → "... Casque de Viking"

**Box Commune :**
- "Livre Raccomodage (x1)" → "Livre Raccommodage (x1)"

**Box Epique :**
- "Oeufs de dragon" → "Oeuf de dragon"

**Box Rare :**
- "Rune de Restoration" → "Rune de Restauration"

### Comment reproduire le bug ?

.

### Qu'aurait-il dû arriver ?

.

### Date et heure de l'apparition problème

30/09

### Serveur

Skyblock

**Comment by SwartZCoding** [comment]
Corrigé ! Merci de ton report
